### ISSUE TITLE
Support unhashing

### ISSUE THREAD

**Issue by konklone** [tgfjt/hubot-hashme#1]
Please add an `unhashme` operation to unhash given hashes with the given algorithm.

**Comment by tgfjt** [comment]
Sounds good... but It seems to be not almost possible.
If we could `unhash`, that `hash` is not secure. meaningless. 
http://en.wikipedia.org/wiki/Security_of_cryptographic_hash_functions#Types_of_security_of_hash_functions

any ideas?

**Comment by konklone** [comment]
This was just me trying to be funny. :smiley_cat: But if you could implement an efficient unhash function, I guarantee you that you would have as much media attention as you could possibly want.

**Comment by tgfjt** [comment]
efficient unhash...!
very scary if already exists:smiling_imp:
