### ISSUE TITLE
Compute the hash for a URL

### ISSUE THREAD

**Issue by parkr** [tgfjt/hubot-hashme#4]
Hi!

Neat thing you have here. What do you think about hashing a document at a given url?

**Comment by parkr** [comment]
Also, what do you think about having a default hashing algorithm so if the first arg isn't an algorithm, then it treats that as the data to hash?

**Comment by tgfjt** [comment]
Hi :smile:

1)
I dont understand well,
Do you want hash `http://example.com/?id=hoge` to `http://example.com/?id=xxxxxxxx`?

2)
Which algorithm do you feel good for default?

**Comment by parkr** [comment]
1. I mean compute the hash for the response of a given URL.
2. I think SHA-1 would be a good default, but that might be biased.

**Comment by tgfjt** [comment]
> 1. I mean compute the hash for the response of a given URL.

Sorry:sweat:, Would you give me an example for it??

Thanks, I'll consider it > default

**Comment by parkr** [comment]
```
hubot hash me http://jekyllrb.com/index.html
```

Hash contents of index.html

**Comment by tgfjt** [comment]
Ah, I got it :+1: 
I'll try it soon.

**Comment by tgfjt** [comment]
@parkr 

> `hubot hash me http://jekyllrb.com/index.html`

done v0.5.1

> default algorithm

I think that having default is not important thing. 

If you have any problem, re-open please!

Thanks.

**Comment by parkr** [comment]
Thanks!!!
